# Generated by Django 4.0.1 on 2022-01-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
