# Generated by Django 4.0.1 on 2022-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='listStr',
        ),
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.JSONField(default={'items': []}),
        ),
    ]
